### PR TITLE
Add some basic lints

### LINKED ISSUE #4: Add basic linting

### PR DESCRIPTION
**Pull request by harsimranmaan**
Closes #4

### CODE REVIEW

**Comment by harsimranmaan** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by harsimranmaan** [comment]
recheckcla

**Comment by harsimranmaan** [comment]
recheckcla

**Comment by harsimranmaan** [comment]
recheckcla

**Comment by harsimranmaan** [comment]
I have read the CLA Document and I hereby sign the CLA

**Review by nicoletamaan — APPROVED** [review]

**Pull request merged**
